# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'winner_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(409, 340)
        Dialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.player = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.player.setFont(font)
        self.player.setScaledContents(True)
        self.player.setAlignment(QtCore.Qt.AlignCenter)
        self.player.setObjectName("player")
        self.verticalLayout.addWidget(self.player)
        self.label_wins = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(108)
        font.setBold(True)
        font.setWeight(75)
        self.label_wins.setFont(font)
        self.label_wins.setAlignment(QtCore.Qt.AlignCenter)
        self.label_wins.setObjectName("label_wins")
        self.verticalLayout.addWidget(self.label_wins)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Game Over"))
        self.player.setText(_translate("Dialog", "TextLabel"))
        self.label_wins.setText(_translate("Dialog", "Wins!"))
